Add field-sizing property
mdn/data pull request #718
Opened 2024-02-29 15:50 UTC by chrisdavidmills

### Description

Chrome 123 supports the `field-sizing` property, which is used to size textual form elements and textareas by their content, rather than sticking to a fixed size. This PR adds data for the new property.

- ChromeStatus: https://chromestatus.com/feature/5176596826161152
- Spec: https://drafts.csswg.org/css-ui/#field-sizing
- Explainer: https://github.com/tkent-google/explainers/blob/main/form-sizing.md

### Motivation

### Additional details

### Related issues and pull requests

2024-04-19 17:02 UTC, dipikabh requested changes
Hi @chrisdavidmills, I have some concerns about the `appliesto` value. I'm wondering if it’s worth all the effort to perfect it. What do you think?

2024-04-21 20:50 UTC, chrisdavidmills commented on css/properties.json
> +    "initial": "normal",
I suspect that was a copy-paste error. Fixed now, thanks for spotting it.

2024-04-21 20:51 UTC, chrisdavidmills commented on css/properties.json
> +    "appliesto": "textFields",
Yeah, this wasn't great. I've added the suggested value `elementsWithDefaultPreferredSize` to the schema and the l10n CSS file, and used it for `field-sizing`.

2024-04-25 15:57 UTC, dipikabh commented on css/properties.json
> +    "appliesto": "textFields",
That's great, thanks!

2024-04-25 15:57 UTC, dipikabh approved these changes
Thanks for the updates and addressing the comments!

2024-04-25 15:57 UTC, merged