feat: Add marker CSS SVG properties
mdn/data pull request #756
Opened 2024-08-15 18:10 UTC by meyerweb

### Description

Adds the properties `marker`, `marker-end`, `marker-mid`, and `,marker-start`.

### Motivation

These properties have already been added to MDN reference content and need the formal syntax data to back them up.

### Related issues and pull requests

Relates to https://github.com/mdn/content/issues/34763.

2024-08-15 18:50 UTC, meyerweb commented
I messed up my branch management, and thus this PR contains commits that are also in #755.  I hope that won’t screw up the process, but if so, let me know what you’d like me to do to fix it.

2024-08-19 23:08 UTC, wbamberg requested changes

2024-08-19 23:08 UTC, wbamberg commented on css/properties.json
> +    "mdn_url": "https://developer.mozilla.org/docs/Web/CSS/shape-outside"
```suggestion
    "mdn_url": "https://developer.mozilla.org/docs/Web/CSS/shape-rendering"
```

?

2024-08-19 23:08 UTC, wbamberg commented on css/properties.json
> +    "initial": "start",
```suggestion
    "initial": "none",
```

?

2024-08-20 14:54 UTC, merged

2024-08-27 04:57 UTC, estelle commented
https://github.com/mdn/data/issues/750