feat(css): Add data for `lighting-color`, `flood-color`, and `flood-opacity`
mdn/data pull request #787
Opened 2024-11-19 21:03 UTC by skyclouds2001

### Description

https://drafts.fxtf.org/filter-effects-1/#FloodOpacityProperty
https://drafts.fxtf.org/filter-effects-1/#FloodColorProperty
https://drafts.fxtf.org/filter-effects-1/#LightingColorProperty

### Motivation

### Additional details

### Related issues and pull requests

Fixes https://github.com/mdn/data/issues/750

2024-11-19 21:03 UTC, skyclouds2001 commented on css/properties.json
> +    "mdn_url": "https://developer.mozilla.org/docs/Web/CSS/flood-color"
```suggestion
    "mdn_url": "https://developer.mozilla.org/docs/Web/CSS/flood-opacity"
```

2024-12-02 13:59 UTC, pepelsbey requested changes
Looks good in general, but there are a bunch of lint issues that need to be fixed before the merge. I tried to fix a few, but it seems like it's not enough.

2024-12-02 17:30 UTC, skyclouds2001 commented on l10n/css.json
>    "limitedSVGElementsPath": {
```suggestion
```

2024-12-02 17:31 UTC, skyclouds2001 commented on l10n/css.json
>    },
```suggestion
```

2024-12-02 17:31 UTC, skyclouds2001 commented on l10n/css.json
> +    "en-US": "{{SVGElement(\"path\")}} element in {{SVGElement(\"svg\")}}"
```suggestion
```

2024-12-02 17:31 UTC, skyclouds2001 commented on l10n/css.json
>    },
```suggestion
```

2024-12-05 16:36 UTC, pepelsbey approved these changes
Looks good! Thank you :)

2024-12-05 16:36 UTC, merged